version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_patterns:
 - "docs/"
 - "snapshots/"
 - "**/*.test.js"
