engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_paths:
 - docs/**/*
ratings:
   paths:
   - "src/**/*"