language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
  - '6'
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
install:
  - yarn install --ignore-engines
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - if: branch = master
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # overwrite default `script` step to skip the tests
      script: echo "Deploying to npm ..."
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
